################################################################
#
# $Id:$
#
# $Log:$
#

#ifeq ($(V),1)
#	VB=''
#else
#	VB=#@
#endif

RV32_ARCH_ABI_FLAGS:=
#RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32im -mabi=ilp32
#RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32im_zba -mabi=ilp32
RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32im_zba_zicond -mabi=ilp32

#RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32ima_zve64x -mabi=ilp32

RV32_CFLAGS:=
#RV32_CFLAGS:=$(RV32_CFLAGS) -nostdlib -nodefaultlibs -nostdinc -static-libgcc
RV32_CFLAGS:=$(RV32_CFLAGS) -nostdlib -nodefaultlibs -nostdinc
RV32_CFLAGS:=$(RV32_CFLAGS) -I /home/fl4shk/local/picolibc/melted_moon_riscv32-unknown-elf/include/
#RV32_CFLAGS:=$(RV32_CFLAGS) -I /home/fl4shk/local/lib/gcc/snowhousecpu-unknown-elf/15.0.1/include
#RV32_CFLAGS:=$(RV32_CFLAGS) -I /opt/riscv32-gnu-toolchain-elf-bin/lib/gcc/riscv32-unknown-elf/15.2.0/include
RV32_CFLAGS:=$(RV32_CFLAGS) -I /home/fl4shk/local/lib/gcc/riscv32-unknown-elf/17.0.0/include
RV32_CFLAGS:=$(RV32_CFLAGS) -O2 -std=gnu99
RV32_CFLAGS:=$(RV32_CFLAGS) $(RV32_ARCH_ABI_FLAGS)
RV32_CFLAGS:=$(RV32_CFLAGS) -DSKINNY_FS_SINT_TYPE=int
RV32_CFLAGS:=$(RV32_CFLAGS) -DSKINNY_FS_BYTE_COUNT_TYPE=int
RV32_CFLAGS:=$(RV32_CFLAGS) -DSKINNY_FS_DEBUG_OUT_OF_RANGE=1
RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_RISCV32=1
RV32_CFLAGS:=$(RV32_CFLAGS) -specs=picolibc.specs
RV32_CFLAGS:=$(RV32_CFLAGS) -mtune=sifive-7-series
RV32_CFLAGS:=$(RV32_CFLAGS) -DCMAP256=1
RV32_CFLAGS:=$(RV32_CFLAGS) -DDOOMGENERIC_RESX=320 -DDOOMGENERIC_RESY=200

RV32_ASFLAGS:=
RV32_ASFLAGS:=$(RV32_ASFLAGS) -march=rv32im -mabi=ilp32


#if (($1 == 1)); then
#    RV32_CFLAGS="$RV32_CFLAGS -DMELTED_MOON_DOOM_TIMEDEMO_3=1"
#    RV32_SUFFIX="-timedemo_3"
#else
#    #RV32_CFLAGS="$RV32_CFLAGS -DMELTED_MOON_DOOM_TIMEDEMO_3=1"
#    RV32_SUFFIX="-no_timedemo"
#fi
#
#if (($2 == 1)); then
#    RV32_CFLAGS="$RV32_CFLAGS -DMELTED_MOON_HAVE_POLL_INFO=1"
#    RV32_SUFFIX="$RV32_SUFFIX-poll_info"
#fi

ifeq ($(DO_TIMEDEMO_3),1)
	RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_DOOM_TIMEDEMO_3=1
	RV32_SUFFIX=-timedemo_3
else
	#RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_DOOM_TIMEDEMO_3=1
	RV32_SUFFIX=-no_timedemo
endif

ifeq ($(DO_POLLINFO),1)
	RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_HAVE_POLL_INFO=1
	RV32_SUFFIX:=$(RV32_SUFFIX)-poll_info
endif
RV32_SUFFIX:=-riscv32$(RV32_SUFFIX)

# subdirectory for objects
OBJDIR=build$(RV32_SUFFIX)
OUTPUT_PREFIX=doomgeneric$(RV32_SUFFIX)
OUTPUT_ELF=$(OUTPUT_PREFIX).elf
OUTPUT_BIN=$(OUTPUT_PREFIX).bin
OUTPUT_DIS=$(OUTPUT_PREFIX)-dis.s

CC=riscv32-unknown-elf-gcc #clang  # gcc or g++
#CFLAGS+=-ggdb3 -Os
CFLAGS:=$(RV32_CFLAGS)
#LDFLAGS+=#-Wl,--gc-sections
LDFLAGS:= \
	$(MY_RV32_ARCH_ABI_FLAGS) \
	-std=gnu99 \
	-Wl,-Bstatic \
	-L/home/fl4shk/local/picolibc/melted_moon_riscv32-unknown-elf/lib \
	-L/home/fl4shk/local/lib/gcc/riscv32-unknown-elf/17.0.0 \
	-L/home/fl4shk/local/lib/gcc/riscv32-unknown-elf/17.0.0/include \
	-specs=picolibc.specs

#CFLAGS+=-ggdb3 -Wall -DNORMALUNIX -DLINUX -DSNDSERV -D_DEFAULT_SOURCE # -DUSEASM
#LIBS+=-lm -lc -lX11
LIBS:= -lc -lgcc -ldummyhost \
	-T melted_moon_doom-riscv32.ld


SRC_DOOM = dummy.c am_map.c doomdef.c doomstat.c dstrings.c d_event.c d_items.c d_iwad.c d_loop.c d_main.c d_mode.c d_net.c f_finale.c f_wipe.c g_game.c hu_lib.c hu_stuff.c info.c i_cdmus.c i_endoom.c i_joystick.c i_scale.c i_sound.c i_system.c i_timer.c memio.c m_argv.c m_bbox.c m_cheat.c m_config.c m_controls.c m_fixed.c m_menu.c m_misc.c m_random.c p_ceilng.c p_doors.c p_enemy.c p_floor.c p_inter.c p_lights.c p_map.c p_maputl.c p_mobj.c p_plats.c p_pspr.c p_saveg.c p_setup.c p_sight.c p_spec.c p_switch.c p_telept.c p_tick.c p_user.c r_bsp.c r_data.c r_draw.c r_main.c r_plane.c r_segs.c r_sky.c r_things.c sha1.c sounds.c statdump.c st_lib.c st_stuff.c s_sound.c tables.c v_video.c wi_stuff.c w_checksum.c w_file.c w_main.c w_wad.c z_zone.c w_file_stdc.c i_input.c i_video.c doomgeneric.c doomgeneric_melted_moon.c skinny_fs.c #doomgeneric_xlib.c
SRC_RV32_ASM_DOOM = melted_moon_doom-asm_funcs-riscv32.s melted_moon_doom-incbin_wad-riscv32.s

OBJS := $(SRC_DOOM:%.c=$(OBJDIR)/%.o)
OBJS_RV32_ASM := $(SRC_RV32_ASM_DOOM:%.s=$(OBJDIR)/%.o)
#OBJS += $(addprefix $(OBJDIR)/, $(SRC_DOOM))
#OBJS_RV32_ASM += $(addprefix $(OBJDIR), $(SRC_RV32_ASM_DOOM))

all:	 $(OUTPUT_BIN) #$(OUTPUT_DIS)

clean:
	rm -rf $(OBJDIR)
	rm -f $(OUTPUT_ELF)
	rm -f $(OUTPUT_BIN)
	rm -f $(OUTPUT_DIS)
	rm -f $(OUTPUT_PREFIX).gdb
	rm -f $(OUTPUT_PREFIX).map

$(OUTPUT_BIN): $(OUTPUT_ELF)
	riscv32-unknown-elf-objcopy -O binary $(OUTPUT_ELF) $(OUTPUT_BIN)

$(OUTPUT_DIS): $(OUTPUT_ELF)
	riscv32-unknown-elf-objdump -D $(OUTPUT_ELF) > $(OUTPUT_DIS)

$(OUTPUT_ELF): $(OBJS) $(OBJS_RV32_ASM)
	@#echo [Linking $@]
	$(VB)$(CC) $(LDFLAGS) $(OBJS) $(OBJS_RV32_ASM) \
	-o $(OUTPUT_ELF) $(LIBS) -Wl,-Map,$(OUTPUT_PREFIX).map
	@#echo [Size]
	@#-$(CROSS_COMPILE)size $(OUTPUT)

$(OBJS): | $(OBJDIR)

$(OBJS_RV32_ASM): | $(OBJDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJS): $(OBJDIR)/%.o: %.c
	@#echo [Compiling $<]
	$(VB)$(CC) $(CFLAGS) -c $< -o $@

$(OBJS_RV32_ASM) : $(OBJDIR)/%.o : %.s
	riscv32-unknown-elf-as $(RV32_ASFLAGS) -c $< -o $@

print:
	@echo OBJS: $(OBJS)

