################################################################
#
# $Id:$
#
# $Log:$
#

#ifeq ($(V),1)
#	VB=''
#else
#	VB=#@
#endif

RV32_ARCH_ABI_FLAGS:=
#RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32im -mabi=ilp32
#RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32im_zba -mabi=ilp32
RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32im_zba_zicond -mabi=ilp32

#RV32_ARCH_ABI_FLAGS:=$(RV32_ARCH_ABI_FLAGS) -march=rv32ima_zve64x -mabi=ilp32

RV32_CFLAGS:=
#RV32_CFLAGS:=$(RV32_CFLAGS) -nostdlib -nodefaultlibs -nostdinc -static-libgcc
RV32_CFLAGS:=$(RV32_CFLAGS) -nostdlib -nodefaultlibs -nostdinc
RV32_CFLAGS:=$(RV32_CFLAGS) -I /home/fl4shk/local/picolibc/melted_moon_riscv32-unknown-elf/include/
#RV32_CFLAGS:=$(RV32_CFLAGS) -I /home/fl4shk/local/lib/gcc/snowhousecpu-unknown-elf/15.0.1/include
#RV32_CFLAGS:=$(RV32_CFLAGS) -I /opt/riscv32-gnu-toolchain-elf-bin/lib/gcc/riscv32-unknown-elf/15.2.0/include
RV32_CFLAGS:=$(RV32_CFLAGS) -I /home/fl4shk/local/lib/gcc/riscv32-unknown-elf/17.0.0/include
RV32_CFLAGS:=$(RV32_CFLAGS) -O2 -std=gnu99
RV32_CFLAGS:=$(RV32_CFLAGS) $(RV32_ARCH_ABI_FLAGS)
RV32_CFLAGS:=$(RV32_CFLAGS) -DTINY_FS_SINT_TYPE=int
RV32_CFLAGS:=$(RV32_CFLAGS) -DTINY_FS_BYTE_COUNT_TYPE=int
RV32_CFLAGS:=$(RV32_CFLAGS) -DTINY_FS_DEBUG_OUT_OF_RANGE=1
RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_RISCV32=1
RV32_CFLAGS:=$(RV32_CFLAGS) -specs=picolibc.specs
RV32_CFLAGS:=$(RV32_CFLAGS) -mtune=sifive-7-series

RV32_ASFLAGS:=
RV32_ASFLAGS:=$(RV32_ASFLAGS) -march=rv32im -mabi=ilp32


#if (($1 == 1)); then
#    RV32_CFLAGS="$RV32_CFLAGS -DMELTED_MOON_DOOM_TIMEDEMO_3=1"
#    RV32_SUFFIX="-timedemo_3"
#else
#    #RV32_CFLAGS="$RV32_CFLAGS -DMELTED_MOON_DOOM_TIMEDEMO_3=1"
#    RV32_SUFFIX="-no_timedemo"
#fi
#
#if (($2 == 1)); then
#    RV32_CFLAGS="$RV32_CFLAGS -DMELTED_MOON_HAVE_POLL_INFO=1"
#    RV32_SUFFIX="$RV32_SUFFIX-poll_info"
#fi

ifeq ($(DO_TIMEDEMO_3),1)
	RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_DOOM_TIMEDEMO_3=1
	RV32_SUFFIX=-timedemo_3
else
	#RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_DOOM_TIMEDEMO_3=1
	RV32_SUFFIX=-no_timedemo
endif

ifeq ($(DO_POLLINFO),1)
	RV32_CFLAGS:=$(RV32_CFLAGS) -DMELTED_MOON_HAVE_POLL_INFO=1
	RV32_SUFFIX:=$(RV32_SUFFIX)-poll_info
endif

# subdirectory for objects
OBJDIR=build$(RV32_SUFFIX)
OUTPUT_PREFIX=doomgeneric$(RV32_SUFFIX)
OUTPUT_ELF=$(OUTPUT_PREFIX).elf
OUTPUT_BIN=$(OUTPUT_PREFIX).bin
OUTPUT_DIS=$(OUTPUT_PREFIX)-dis.s

CC=riscv32-unknown-elf-gcc #clang  # gcc or g++
#CFLAGS+=-ggdb3 -Os
CFLAGS:=$(RV32_CFLAGS)
#LDFLAGS+=#-Wl,--gc-sections
LDFLAGS:= \
	$(MY_RV32_ARCH_ABI_FLAGS) \
	-Wl,-Bstatic \
	-L/home/fl4shk/local/picolibc/melted_moon_riscv32-unknown-elf/lib \
	-L/home/fl4shk/local/lib/gcc/riscv32-unknown-elf/17.0.0 \
	-L/home/fl4shk/local/lib/gcc/riscv32-unknown-elf/17.0.0/include \
	#-specs=picolibc.specs

#CFLAGS+=-ggdb3 -Wall -DNORMALUNIX -DLINUX -DSNDSERV -D_DEFAULT_SOURCE # -DUSEASM
#LIBS+=-lm -lc -lX11
LIBS+= \
	-lgcc -lc -ldummyhost \
	-T melted_moon_doom-riscv32.ld


SRC_DOOM = dummy.o am_map.o doomdef.o doomstat.o dstrings.o d_event.o d_items.o d_iwad.o d_loop.o d_main.o d_mode.o d_net.o f_finale.o f_wipe.o g_game.o hu_lib.o hu_stuff.o info.o i_cdmus.o i_endoom.o i_joystick.o i_scale.o i_sound.o i_system.o i_timer.o memio.o m_argv.o m_bbox.o m_cheat.o m_config.o m_controls.o m_fixed.o m_menu.o m_misc.o m_random.o p_ceilng.o p_doors.o p_enemy.o p_floor.o p_inter.o p_lights.o p_map.o p_maputl.o p_mobj.o p_plats.o p_pspr.o p_saveg.o p_setup.o p_sight.o p_spec.o p_switch.o p_telept.o p_tick.o p_user.o r_bsp.o r_data.o r_draw.o r_main.o r_plane.o r_segs.o r_sky.o r_things.o sha1.o sounds.o statdump.o st_lib.o st_stuff.o s_sound.o tables.o v_video.o wi_stuff.o w_checksum.o w_file.o w_main.o w_wad.o z_zone.o w_file_stdc.o i_input.o i_video.o doomgeneric.o skinny_fs.o #doomgeneric_xlib.o
OBJS += $(addprefix $(OBJDIR)/, $(SRC_DOOM))

all:	 $(OUTPUT_ELF)

clean:
	rm -rf $(OBJDIR)
	rm -f $(OUTPUT_ELF)
	rm -f $(OUTPUT_BIN)
	rm -f $(OUTPUT_DIS)
	rm -f $(OUTPUT_PREFIX).gdb
	rm -f $(OUTPUT_PREFIX).map

$(OUTPUT_ELF):	$(OBJS)
	@#echo [Linking $@]
	$(VB)$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) \
	-o $(OUTPUT_ELF) $(LIBS) -Wl,-Map,$(OUTPUT_PREFIX).map
	@#echo [Size]
	@#-$(CROSS_COMPILE)size $(OUTPUT)

$(OBJS): | $(OBJDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o:	%.c
	@#echo [Compiling $<]
	$(VB)$(CC) $(CFLAGS) -c $< -o $@

print:
	@echo OBJS: $(OBJS)

